### ISSUE TITLE
Not always seeing Join events

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#10]
I don't know if the framework is blind to "joins" but I see "user has left #baldengineer" without a join.

Maybe it is only printing a status update if the user is "new" / not known? (I see those.)

**Comment by tisboyo** [comment]
I believe this is due to the way twitch irc announces user join/departs but I will research it.

**Comment by tisboyo** [comment]
So this is definitely a problem with Twitch chat, https://discuss.dev.twitch.tv/t/irc-join-part-events-delayed-significantly/15519
But the last comment in that thread has an endpoint with current viewers, need to do some tests on that.

**Comment by tisboyo** [comment]
@baldengineer

**Comment by tisboyo** [comment]
https://dev.twitch.tv/docs/irc/guide#twitch-irc-capabilities maybe if we can get the framework to negotiate as IRC v3, it will get the announcements more often.

**Comment by baldengineer** [comment]
For my clarification, the issue is that you aren't receiving the events. Not that the bot is missing them?

**Comment by tisboyo** [comment]
> 
> 
> For my clarification, the issue is that you aren't receiving the events. Not that the bot is missing them?

Correct, unfortunately.

**Comment by baldengineer** [comment]
If you want to close this one, you can. With chatty I can see the behavior is on the Twitch side. I doubt it is going to change any time soon.

**Comment by tisboyo** [comment]
sounds good..
