### ISSUE TITLE
Add !uptime command

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#110]
Streamlabs has the "!uptime" command, which replies with how long the stream has been going. I'm not sure if it gets it from Twitch or if it just starts counting from when it notices the stream going live.

I would like to enable such a command.

User: !uptime
Bot: The stream has been live for X hours and Y minutes.

**Comment by tisboyo** [comment]
Docs: https://dev.twitch.tv/docs/api/reference#get-streams
