### ISSUE TITLE
Record and announce hosts

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#113]
Since I (seem to miss) Hosts on the activity feed, it'd be great if the bot could say in chat when someone is hosting.

**Comment by tisboyo** [comment]
Currently unable to find an end point that does this. Still researching.

**Comment by tisboyo** [comment]
https://tmi.twitch.tv/hosts?include_logins=1&target=125957551 returns the channels hosting... 

Sample
`{"hosts":[{"host_id":144676560,"target_id":491459194,"host_login":"8michi","host_display_name":"8michi"},{"host_id":9092112,"target_id":491459194,"host_login":"feliciaday","host_display_name":"FeliciaDay"},{"host_id":107413894,"target_id":491459194,"host_login":"aflyingbrickington","host_display_name":"AFlyingBrickington"},{"host_id":613148297,"target_id":491459194,"host_login":"javenescobar","host_display_name":"JavenEscobar"},{"host_id":18907996,"target_id":491459194,"host_login":"jackfletcher","host_display_name":"JackFletcher"}]}`

Going to require checks on a schedule. Maybe only do them while the stream is active to prevent excessive queries.

**Comment by tisboyo** [comment]
Also, this is part of the old api and could be depreciated at any point.

**Comment by tisboyo** [comment]
This is going to be dependent on #123, so delaying implementation.

**Comment by tisboyo** [comment]
May have found a new method of capturing these, msg.msg-id == 'host_success_viewers'
Needs tested when stream is live.

**Comment by tisboyo** [comment]
Interesting quote from https://discuss.dev.twitch.tv/t/irc-not-receiving-notice-when-there-is-an-incoming-host/23366/2

> Host notifications are only sent to the broadcasters chat feed so you’ll have to logged into chat as the broadcaster ie same user as the channel.

Tested streaming on main account and hosting on bot account for 10 minutes and never received a notification.

**Comment by tisboyo** [comment]
Logged in with streamer account on bot and still received no notices of the host.
Starting to suspect a permission issue, maybe streamlabs is requesting a permission we aren't so they are able to get that data.

**Comment by tisboyo** [comment]
For future reference
`streamlabs_scope = [
    "user_read",
    "channel_subscriptions",
    "user_subscriptions",
    "chat:read",
    "channel_editor",
    "bits:read",
    "channel:read:subscriptions",
    "channel:read:polls",
    "channel:manage:polls",
]`

**Comment by tisboyo** [comment]
Attempted using streamlabs permissions plus the ones we had before and still never got an autohost notification using the bot account. There has to be a hidden endpoint they have access to.

**Comment by tisboyo** [comment]
Not looking like this is going to happen soon, but I'm not forgetting about it.
Closed.
