### ISSUE TITLE
Add blacklist of known bots following regex patterns

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#124]
Not sure if this should be one-off or if there should be hooks for regex or pattern rules. But there are certain "bot" accounts that follow channels. An example is "hederXXXXXX" where XXXXXX is a 6 digit incrementing number.

I don't want the bot to "thank" these kinds of accounts.

In this case, the rule would either be:

- any user name that starts with "heder"
- username "heder" followed by numbers
- username "heder" followed by 6 numbers

For now, I would be happy if the bot didn't thank accounts that started with "heder" and ended with a series of numbers.

**Comment by tisboyo** [comment]
regex - `/heder[0-9]{6}/`

**Comment by tisboyo** [comment]
Add a table to track known bots and a method of completely ignoring them from all aspects of the bot except logging. 
No commands, no greetings, no thanks, etc.
