### ISSUE TITLE
Add a command to disable treatbot emojis when in office

### ISSUE THREAD

**Issue by tisboyo** [tisboyo/Twitch_Bot#128]
^

**Comment by tisboyo** [comment]
Maybe an !office and !lab commands to set proper flags.. Thoughts @baldengineer ?

**Comment by tisboyo** [comment]
Partially implemented in #123 by adding `!stream lab` and `!stream office` commands.

**Comment by tisboyo** [comment]
This disables the TreatBot when in the office.
@baldengineer are there any other things you want to be location specific?

**Comment by tisboyo** [comment]
- [ ] Add GetAttention and other notifiers.
- [ ] Add Announce location when going live

**Comment by baldengineer** [comment]
please add the location to the stream "starting" chat message. To serve as a reminder.

**Comment by baldengineer** [comment]
otherwise, !stream lab and !stream office commands are acceptable.

When we talked, I asked to disable the notifier and treatbot. I am changing my mind on the notifier. Do not disable it. I will start moving it (or make another one.)

**Comment by tisboyo** [comment]
With the NDI setup, I am not going to disable the treatbot either now, I suppose?
