### ISSUE TITLE
Shoutout command - raid and specified

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#150]
Add command to shout-out to raids, hosts, or a specified username.

Command:
`!so`
This command should shout-out to the last host or raider.

`!so <username>`
Send shout-out to that username.

Example shoutout statements (configurable?)

- Hey Everyone! Check out the awesome <username>. Give them a follow!
- Happy to see <username> here, send them a balden3Yay!
- Now that <username> is here, we can get started. j/k. But we CAN give them a follow.

**Comment by tisboyo** [comment]
Reopening, the base !so command without specifying is apparently not working correctly.
