### ISSUE TITLE
Trivia: Database Sync

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#151]
Provide a method to upload the "questions.txt" to the server and process it.

The intention is to sync question id so that the bot can do things with the questions.

For example, post the current question in chat and track correct answers.

**Comment by tisboyo** [comment]
Further enhancement:

- [ ] Allow upload of questions.txt from web interface. Requires completion of #154 
- [ ] Allow download of questions.txt from web interface. Requires completion of #154

Moving milestone to April to coincide with #154

**Comment by tisboyo** [comment]
Holding for #154 to be complete, moving to [May](https://github.com/tisboyo/Twitch_Bot/milestone/7)

**Comment by tisboyo** [comment]
Holding for #154 to be complete, moving to [June21](https://github.com/tisboyo/Twitch_Bot/milestone/11)
