### ISSUE TITLE
Trivia: Post Questions in Chat and Track correct answers

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#152]
Get a message from my trivia script containing the current question id. after a changeable delay time, post the question in chat and then track who users answer the question correctly. (can accept multiple answers, but only the last one counts.)

Should have a warning after 20 seconds (configurable - warning threshold), saying there are 5 seconds left. And stop accepting answers after 25 seconds.

So: 
- delay time
- time remaining warning
- accept answer time

Ideally, I'd like a way to get who got the answers right. So that a) the bot congrats them in chat and b) I can put their username on screen.

**Comment by tisboyo** [comment]
Posting is working. Tracking is not there yet.
