### ISSUE TITLE
Tutorial: I need some 1-on-1 time for how to do things with the bot server

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#181]
Placeholder for us to talk about when we can do a screen share.

1. How to reboot the bot correctly. (I might have notes on this, but let's review)
2. Restart just the bot
3. Get the `screen` back to the logging/console information
4. Anything else James should know...

**Comment by tisboyo** [comment]
Is this one still needed?

**Comment by baldengineer** [comment]
No. Also, I can ask you questions in two weeks.
