### ISSUE TITLE
Database model column size too small for CustomCommand/response

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#182]
I was trying to update the custom `!gear` command. So I deleted it and tried to re-add. However, the bot doesn't respond to the command (or add it).

```!addcmd !gear SCOPE: R&S RTM3004 or Multicomp Tablet MP720645. DMM: Multicomp MP730026. SOLDER: Weller WXR-3. P/S: Tenma Portable. TAPE: Scotch/3M Blue Masking. CAM-A: Panasonic GH-5. CAM-B: Panasonic G7. LAV MIC: Sony UWP-D11. CARdOID: Rode NT1a w/ GoXLR Mini. Tons. Of. Lights.```

It doesn't seem to like something about that. I tried shortening by about half the characters, but no go. I also tested adding/removing another command it that worked as expected.

**Comment by tisboyo** [comment]
(mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'response' at row 1

Need to investigate the database models to see if they are too short.

**Comment by baldengineer** [comment]
That’s interesting. Something changed then because I copy/pasted the old command’s text and it didn’t work either. So the column was big enough at some point.

**Comment by tisboyo** [comment]
Currently limited to 255 characters. https://github.com/sharkbound/PythonTwitchBotFramework/blob/49ae6950d8dc854e59173b883f11a553ae08bce0/twitchbot/database/models.py#L32

Not sure if that is something he will be willing to change as there could be unexpected results from making changes like that.
However, I can hardcode the command as a standalone to at least achieve the desired result.

**Comment by baldengineer** [comment]
No, don't hard code it. I'll figure out something else.

**Comment by tisboyo** [comment]
response column in CustomCommand model is too small (255). Investigate increasing the size and the negative impacts on that.
