### ISSUE TITLE
Need !topic command to update topic

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#194]
Currently, the only way to update the topic is to use the `!topic set` command. Which, resets the goal, step, and link. I'd like a command or way to update the topic itself (like when I find a typo after resetting the other three...)

maybe something silly like `!topic topic`

**Comment by tisboyo** [comment]
How about a !topic reset that deletes everything and !topic set works as described here?

**Comment by baldengineer** [comment]
Yes. That would work.
