### ISSUE TITLE
Minor, unhandled pubsub: clear chat

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#215]
```
twitchbot_bot           | Unknown pubsub received: {'type': 'chat_channel_modera
user_id': '', 'target_user_login': '', 'from_automod': False}
```

Got that when I used the "Clear Chat" today. I was trying to clear my chat window, I guess "Clear Chat" means everyone's chat?

![Image 2021-05-28 14_11_06](https://user-images.githubusercontent.com/719836/120031561-cfb62400-bfad-11eb-86fb-f7620c5e2c7f.png)

**Comment by tisboyo** [comment]
Yep, the bot is just notifying us that it received a pubsub event and doesn't know what to do with it, so it's giving us all of the data from it in case we want to use it for something. Comes from https://github.com/tisboyo/Twitch_Bot/blob/fa3b74a2554345b2b0bc9fd1db7f0d6c0c9c1e01/bot/mods/logger.py#L82-L83

Is there something we want to do with this event?

**Comment by baldengineer** [comment]
At first, I thought no action. But could you add something in the IRQ logs that the event occured?

It might be useful if we ever have to track back something that happened in chat.
