### ISSUE TITLE
Here's a big one ... !clip command and database

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#221]
Let's create a listing of clips. We need to store:
1. Clip Shortcut name
2. Clip URL

Adding would look something like this:
`!clip add mathishard https://....`
Ideally... if the Twitch API lets you get the title of the clip, that would be nice to add to the database as well.

Accessing would be something like:
`!clip mathishard`

If used alone `!clip` should return a random clip. (With a 5-minute timeout for random clips)

## Editing
Will also need an edit (to change the name or URL) and delete. (Similar to announcements).

I would like the VIP role to be able to add clips (but not edit or delete.)

## Listing
Ideally, a list of clips should be available on the web interface, similar to announcements. While that URL is not publically accessible, I would like:
`!clip list` to return a URL: `https://bald.ee/stream-clip-list`

Now. Before you freak out. That URL will bounce to `baldengineer.com/something`. `Something` will be a script that gets the list from the bot on the server-side. Clients will never see the bot.

**Comment by baldengineer** [comment]
Here's a list to get started (these are the !quote from streamlabs)

- mathisfun
- https://www.twitch.tv/baldengineer/clip/PatientDeliciousCockroachNononoCat

- spaces
- https://www.twitch.tv/baldengineer/clip/KitschyRefinedPandaWoofer

- whoa
- https://www.twitch.tv/baldengineer/clip/SplendidAstuteBatOhMyDog

- fisfun
- https://www.twitch.tv/baldengineer/clip/RudeLittleBottleOneHand

- bluetape
- https://clips.twitch.tv/IgnorantDullMarjoramDxCat

- baldpnp
- https://clips.twitch.tv/GloriousFantasticOryxKevinTurtle

**Comment by tisboyo** [comment]
Currently set for a 5 minute delay between !clip commands
