### ISSUE TITLE
Discord bot does not have permission to bake me a cake.

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#270]
Can you please adjust bot's oauth permissions to allow discord to bake me a cake?

kthxbai.

![image](https://user-images.githubusercontent.com/719836/133933820-abdfcd4b-0d8d-4f2f-9faa-90a7a7782a74.png)

**Comment by tisboyo** [comment]
I'm sorry, but building a cake baking robot is out of scope.

**Comment by sher9n** [comment]
This is still an issue, any resolution? :)

**Comment by AADI0009** [comment]
i wann cake :/
