### ISSUE TITLE
Way to send commands without using chat

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#61]
Example would be to send commands from a web page or the bot's command line. To avoid having !commands show up in chat.

**Comment by tisboyo** [comment]
Checked in with Sharkbound, this is still a WIP on the framework side.

**Comment by tisboyo** [comment]
Just checked the framework, and while he has started on the ability to do this, it's still not there. Going to push this to Jan21 milestone.

**Comment by sharkbound** [comment]
in version 2.1.4 this is possible by sending the command json to the command server: 
```
{
    "channel": "channel here", 
    "command": "command here",
    "args": ["arg1", "arg2", "ect"],
    "silent": true
}```
if slient is true, then all output command output will be relayed to the bot's console instead of chat

**Comment by tisboyo** [comment]
> ```
> {
>     "type":"run_command",
>     "channel": "channel here", 
>     "command": "command here",
>     "args": ["arg1", "arg2", "ect"],
>     "silent": true
> }
> ```
I was a little confused about the missing type. Documenting here for reference.
