### ISSUE TITLE
Host MQTT server

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#62]
Transition away from Adafruit IO.

Concerns:

1. Authentication
2. Can ESP8266 do SSL?

Goal for end of December is a plan to transition.

**Comment by tisboyo** [comment]
warning: When enabling this in other scripts, make sure certifi is up to date. I spent more then a few hours chasing that one only to find it in a random issue eclipse/paho.mqtt.python#85

**Comment by tisboyo** [comment]
Warning: make sure to update certifi when using connecting in other scripts, https://github.com/eclipse/paho.mqtt.python/issues/85

**Comment by tisboyo** [comment]
A resource that may be useful for arduino https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/updating-ssl-certificates

**Comment by woshiluoyong** [comment]
> Warning: make sure to update certifi when using connecting in other scripts, [eclipse/paho.mqtt.python#85](https://github.com/eclipse/paho.mqtt.python/issues/85)
> 
> Also, for paho.mqtt don't forget to do `client.tls_set()` to enable TLS. If unable to get certifi to update do `client.tls_set(cert_reqs=ssl.CERT_NONE)`

Good
