### ISSUE TITLE
Create "event point" system to trigger actions (like OBS sources)

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#72]
Need to support combination of redemption acitivites.

e.g. 10 Channel Point redeems, cheers, and/or command from VIPs.

The intent is to move !treatme command to require community interaction

**Comment by baldengineer** [comment]
To further explain this concept. I want an action to occur based on a variety of events. The events should have points associated with them and accumulate until firing the action. I want the action to either be automatic or manual. 

If automatic, then the event fires when enough points build up. And if manual, then I'll press a button or issue a command to execute. In both cases, once fired, the count should reset.

### Manual Example: !treatme
We would re-purpose the command. 

Event point breakdown:
- "treat me" emote is worth 1 point (need to create this one.)
- Channel Point Redemption is worth 5 points
- Cheer Bits are worth 10 points per bit
Subscribers should have a multiplier, default of 2X.

As the events occur, the points build up. When I do the !treatme command (or some other trigger), then reset the points to zero.   

For reference, my plan is to run the treatbot for time based on the amount of points. So, at a break, when someone raids, or at the end, I can "redeem" my treats. 

The bot should respond with a point update in chat. And then I want to look at some web-based message that we can flash on screen. (Not asking you to do the web part yet, but think about how we might be able to hook into that.)

### Automatic Example: Balden3Yay!
In this case, it would take a set number of points to activate a source. 

Event points:
- balden3Yay emote: 5 pts
Subscribers should have a multiplier, 2X.

Needs to have a configurable cooldown time and event count. 

For example, up to 3 events and then a 5-minute cooldown. Or another way to say it, from the first firing, start a timer. Then allow the event to process 2 more times. Then stop firing until the initial 5-minute cooldown expires. This does mean if it gets triggered and then 4 minutes, 50 seconds later it can get triggered again. then 15 seconds after that, it could get triggered 3 times in a row, so effectively 4 times in a row. Make sense? :)

**Comment by baldengineer** [comment]
changed name from "Create "voting" system for command" to "event point" system. The title better describes this enhancement.

Also starting to realize this may represent a more significant effort than I originally thought.

**Comment by tisboyo** [comment]
Todo still:

- [ ] Add yay cooldown command
- [ ] Add time reset in Points class (x minutes from first trigger)

I feel like a treat cooldown isn't required because it requires a mod_command to initiate.
