### ISSUE TITLE
Unknown Pubsub when banning (bots)

### ISSUE THREAD

**Issue by baldengineer** [tisboyo/Twitch_Bot#8]
`Unknown pubsub received: {'type': 'chat_login_moderation', 'moderation_action': 'ban', 'args': ['lilwashu', ''], 'created_by': 'baldengineer', 'created_by_user_id': '125957551', 'msg_id': '', 'target_user_id': '29686800', 'target_user_login': '', 'from_automod': False}`

**Comment by tisboyo** [comment]
New one I haven't seen before. Will add it to the handler. 

Is there a need to do anything with the data at the moment?
Ignore it, log it, other?

**Comment by baldengineer** [comment]
For now, let's just log it. Might be easier to have our own log for when someon whines about getting banned "for no reason!"
